---
title: "Make PHV Inputs"
author: "Dominik Schneider"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Predictor Variables

These are the predictors currently being used to estimate SWE. If you add/remove any then the formula in `gnet_fsca.r` needs to be updated accordingly. For a domain name of `ucrb`, they must be labeled `ucrb_dem.tif` (for elevation). The package will use all geotif files in the `data/phv` folder and parse the name based on the underscore. Each geotif should have the same resolution, extent, grid etc. and should match the values for extent and resolution given in the run file for fSCA. The package was built to use MODIS fSCA so resolution in degrees is 15/3600 or 0.0041666666667 (converted from the modis sinusoidal projection). The projection should be lat/long wgs84 (+epsg=4326)

* dem (elevation)
* lat (latitude)
* long (longitude)
* eastness (sine of aspect)
* northness (cosine of aspect)
* zness (sine of slope)
* regionaleastness (sine of aspect at 4km resolution)
* regionalnorthness (cosine of aspect at 4km resolution)
* regionalzness (sine of slope at 4km resolution)
* dist2coast (shortest distance to the ocean)
* dist2contdiv (shortest distance to the continental divide. pixels west of the divide are negative)

for now making phv inputs is only documented for the `idwy` domain on [github](https://github.com/hoargroup/example_sweRegression/blob/master/idwy/preprocess_phv/create_input_rasters.R). Raw text file is [here](https://raw.githubusercontent.com/hoargroup/example_sweRegression/master/idwy/preprocess_phv/create_input_rasters.R)
